SYSTEM = "You are AGE years old, your gender is GENDER and your employment status is best "\
    "described as EMPLOYMENT_STATUS. With machine learning models and intelligent agents, you "\
    "have AI_USER experience as a user and AI_DEV experience as a developer. You are confronted "\
    "with a user study survey. Give answers in tune with your personality and previous answers if "\
    "there are any."
    
USER ="Attached is an image that consists of two sub-images. The top of the given image displays "\
    "the original image of a bird and the bottom displays the same image combined with a heatmap "\
    "that was generated by an explainable artificial intelligence (XAI) model to predict the species. "\
    "You think the model distinguishes the four possible species classes based on the following "\
    "features if they are highlighted red by the heatmap:\n"\
    "- Rhinoceros Auklets: HEATMAP_FEATURES_RA\n"\
    "- Least Auklets: HEATMAP_FEATURES_LA\n"\
    "- Parakeet Auklets: HEATMAP_FEATURES_PA\n"\
    "- Crested Auklets: HEATMAP_FEATURES_CA\n"\
    "Based on the descriptions and the areas highlighted by the heatmap, what bird species do you "\
    "think did the XAI model predict for the given image?"\
    "Use the areas highlighted red in the bottom image for you answer by comparing them to the given description. If multiple "\
    "answers seem equally reasonable, choose one randomly. Do not use other knowledge about the bird " \
    "species. Your answer might differ from the actual species of the shown bird."\
    "For your answer, choose one of the following options:\n"\
    "- Crested Auklet\n"\
    "- Least Auklet\n"\
    "- Parakeet Auklet\n"\
    "- Rhinoceros Auklet\n"\
    "For each description explain why it could be this bird species or why not. Then, at the end, state the concluded bird species prediction "\
    "by mentioning only the selected species in the last line of your answer."  

USER_ALT = "Attached is an image of a bird augmented with a heatmap. The heatmap "\
    "was generated by an explainable artificial intelligence (XAI) model to predict the bird species. "\
    "You think the model distinguishes the four possible species classes based on the following "\
    "features if they are highlighted by the heatmap:\n"\
    "- Rhinoceros Auklets: HEATMAP_FEATURES_RA\n"\
    "- Least Auklets: HEATMAP_FEATURES_LA\n"\
    "- Parakeet Auklets: HEATMAP_FEATURES_PA\n"\
    "- Crested Auklets: HEATMAP_FEATURES_CA\n"\
    "Based on the descriptions and the areas highlighted by the heatmap, what bird species do you "\
    "think did the XAI model predict for the given image?"\
    "Use the areas highlighted red in the image for you answer by comparing them to the given description. If multiple "\
    "answers seem equally reasonable, choose one randomly. Do not use other knowledge about the bird " \
    "species. Your answer might differ from the actual species of the shown bird."\
    "For your answer, choose one of the following options:\n"\
    "- Crested Auklet\n"\
    "- Least Auklet\n"\
    "- Parakeet Auklet\n"\
    "- Rhinoceros Auklet\n"\
    "For each description explain why it could be this bird species or why not. Then, at the end, state the concluded bird species prediction "\
    "by mentioning only the selected species in the last line of your answer."   


USER_AGREEMENT_INTRO = "You were given images of birds augmented with a heatmap. The heatmap "\
    "was generated by an explainable artificial intelligence (XAI) model to predict the bird species. "\
    "You were asked to describe what features the model pays attention to based on the heatmap. You "\
    "answered the following:\n" \
    "- Rhinoceros Auklets: HEATMAP_FEATURES_RA\n"\
    "- Least Auklets: HEATMAP_FEATURES_LA\n"\
    "- Parakeet Auklets: HEATMAP_FEATURES_PA\n"\
    "- Crested Auklets: HEATMAP_FEATURES_CA\n"\
    "Afterwards you had to guess which of the four bird species was used to classify given images augmented " \
    "with heatmaps created by the XAI model. Out of 20 images, you guessed the classification correctly for " \
    "CORRECT_CLASSIFICATIONS of them. Now you are asked to evaluate your XAI user study experience."


USER_AGREEMENT_QUESTION = ""


USER_OLD ="Attached is an image that consists of two sub-images. The top of the given image displays "\
    "the original image of a bird and the bottom displays the same image combined with a heatmap "\
    "that was generated by an explainable artificial intelligence (XAI) model to predict the species. "\
    "You think the model distinguishes the four possible species classes based on the following "\
    "features:\n"\
    "- Rhinoceros Auklets: HEATMAP_FEATURES_RA\n"\
    "- Least Auklets: HEATMAP_FEATURES_LA\n"\
    "- Parakeet Auklets: HEATMAP_FEATURES_PA\n"\
    "- Crested Auklets: HEATMAP_FEATURES_CA\n"\
    "Which of these features are highlighted in the bottom image and what bird species do you "\
    "think did the XAI model predict for the image?"\
    "Choose one of the following options:\n"\
    "- Crested Auklet\n"\
    "- Least Auklet\n"\
    "- Parakeet Auklet\n"\
    "- Rhinoceros Auklet\n"\
    "Answer with the bird name only."